// Dashboard data — generated from CSVs. Regenerate via
// python -c "<this script>" from the repo root.

window.DATA = {
  mc: [
  {
    "topic": "T1 Water Resilience & Equitable Access",
    "impact_mean": 3.979041831203865,
    "impact_p5": 3.8672948087758727,
    "impact_p50": 3.977839169966325,
    "impact_p95": 4.093632076098472,
    "financial_mean": 3.0725679042817973,
    "financial_p5": 2.850868539174624,
    "financial_p50": 3.071394322151068,
    "financial_p95": 3.3019113232419715,
    "ellipse_width": 0.5847284250320702,
    "ellipse_height": 0.294816778238312,
    "ellipse_angle": -179.94059501010025,
    "in_target_zone": true
  },
  {
    "topic": "T2 Digital & Cyber Infrastructure",
    "impact_mean": 3.0815738028766475,
    "impact_p5": 2.9251669631949127,
    "impact_p50": 3.0819920650526407,
    "impact_p95": 3.2427250925516127,
    "financial_mean": 2.7467839677922825,
    "financial_p5": 2.5035628330167974,
    "financial_p50": 2.738912475172733,
    "financial_p95": 3.0127303786783,
    "ellipse_width": 0.658360230587086,
    "ellipse_height": 0.4120853972188094,
    "ellipse_angle": -179.99878170642128,
    "in_target_zone": true
  },
  {
    "topic": "T3 Green Finance & Integrity",
    "impact_mean": 3.2430733399435128,
    "impact_p5": 3.078901306573376,
    "impact_p50": 3.242521790323922,
    "impact_p95": 3.409013839297668,
    "financial_mean": 2.421648789462025,
    "financial_p5": 2.2378600232478645,
    "financial_p50": 2.420944189452072,
    "financial_p95": 2.61066978498776,
    "ellipse_width": 0.4827616143293209,
    "ellipse_height": 0.4308515529870557,
    "ellipse_angle": -179.4813739988564,
    "in_target_zone": false
  }
],
  aqueduct: [
  {
    "country": "Spain",
    "iso3": "ESP",
    "region_label": "Segura basin (Murcia + parts of Alicante)",
    "bws_category_2024": "Extremely High",
    "bws_score_2024": 4.6,
    "bws_category_2030_BAU": "Extremely High",
    "bws_score_2030_BAU": 4.7,
    "revenue_share_pct": 14,
    "satisfaction_2024": 88.0,
    "concession_note": "Core concession; reuse + desalination CAPEX imperative"
  },
  {
    "country": "Spain",
    "iso3": "ESP",
    "region_label": "Guadalquivir basin (Andalucía)",
    "bws_category_2024": "High",
    "bws_score_2024": 3.6,
    "bws_category_2030_BAU": "Extremely High",
    "bws_score_2030_BAU": 4.2,
    "revenue_share_pct": 12,
    "satisfaction_2024": 88.0,
    "concession_note": "Drought-cycle OPEX volatility"
  },
  {
    "country": "Spain",
    "iso3": "ESP",
    "region_label": "Guadiana / Tagus (Madrid + Extremadura)",
    "bws_category_2024": "Medium-High",
    "bws_score_2024": 2.8,
    "bws_category_2030_BAU": "High",
    "bws_score_2030_BAU": 3.4,
    "revenue_share_pct": 15,
    "satisfaction_2024": 88.0,
    "concession_note": "Seasonal stress; storage-dependent"
  },
  {
    "country": "Spain",
    "iso3": "ESP",
    "region_label": "Cantabrian + Galician",
    "bws_category_2024": "Low-Medium",
    "bws_score_2024": 1.4,
    "bws_category_2030_BAU": "Medium-High",
    "bws_score_2030_BAU": 2.3,
    "revenue_share_pct": 14,
    "satisfaction_2024": 88.0,
    "concession_note": "Low stress today; climate-driven uptick by 2030"
  },
  {
    "country": "Portugal",
    "iso3": "PRT",
    "region_label": "Algarve + Alentejo",
    "bws_category_2024": "High",
    "bws_score_2024": 3.5,
    "bws_category_2030_BAU": "Extremely High",
    "bws_score_2030_BAU": 4.2,
    "revenue_share_pct": 6,
    "satisfaction_2024": 65.0,
    "concession_note": "Tourism-driven demand volatility"
  },
  {
    "country": "Portugal",
    "iso3": "PRT",
    "region_label": "Porto / Douro",
    "bws_category_2024": "Medium-High",
    "bws_score_2024": 2.5,
    "bws_category_2030_BAU": "High",
    "bws_score_2030_BAU": 3.3,
    "revenue_share_pct": 2,
    "satisfaction_2024": 65.0,
    "concession_note": "Lower stress north"
  },
  {
    "country": "Italy",
    "iso3": "ITA",
    "region_label": "Po basin / Lombardy",
    "bws_category_2024": "High",
    "bws_score_2024": 3.7,
    "bws_category_2030_BAU": "Extremely High",
    "bws_score_2030_BAU": 4.3,
    "revenue_share_pct": 6,
    "satisfaction_2024": 67.0,
    "concession_note": "2022 drought was a record; recurring risk"
  },
  {
    "country": "Italy",
    "iso3": "ITA",
    "region_label": "Sicily",
    "bws_category_2024": "Extremely High",
    "bws_score_2024": 4.6,
    "bws_category_2030_BAU": "Extremely High",
    "bws_score_2030_BAU": 4.8,
    "revenue_share_pct": 3,
    "satisfaction_2024": 67.0,
    "concession_note": "Structural scarcity"
  },
  {
    "country": "Italy",
    "iso3": "ITA",
    "region_label": "Central / Umbria",
    "bws_category_2024": "Medium-High",
    "bws_score_2024": 2.7,
    "bws_category_2030_BAU": "High",
    "bws_score_2030_BAU": 3.2,
    "revenue_share_pct": 3,
    "satisfaction_2024": 67.0,
    "concession_note": "Moderate today"
  },
  {
    "country": "France",
    "iso3": "FRA",
    "region_label": "Languedoc / Provence",
    "bws_category_2024": "High",
    "bws_score_2024": 3.4,
    "bws_category_2030_BAU": "Extremely High",
    "bws_score_2030_BAU": 4.1,
    "revenue_share_pct": 4,
    "satisfaction_2024": 86.0,
    "concession_note": "Climate-driven stress rising"
  },
  {
    "country": "France",
    "iso3": "FRA",
    "region_label": "Other regions",
    "bws_category_2024": "Medium-High",
    "bws_score_2024": 2.4,
    "bws_category_2030_BAU": "High",
    "bws_score_2030_BAU": 3.0,
    "revenue_share_pct": 1,
    "satisfaction_2024": 86.0,
    "concession_note": "Stable"
  },
  {
    "country": "Czech Republic",
    "iso3": "CZE",
    "region_label": "Moravia / Bohemia",
    "bws_category_2024": "Low-Medium",
    "bws_score_2024": 1.6,
    "bws_category_2030_BAU": "Medium-High",
    "bws_score_2030_BAU": 2.5,
    "revenue_share_pct": 7,
    "satisfaction_2024": 90.0,
    "concession_note": "Stable supply; resilience partner market"
  },
  {
    "country": "Colombia",
    "iso3": "COL",
    "region_label": "Cundinamarca (Bogotá) - Paramo-fed",
    "bws_category_2024": "Medium-High",
    "bws_score_2024": 2.9,
    "bws_category_2030_BAU": "High",
    "bws_score_2030_BAU": 3.5,
    "revenue_share_pct": 4,
    "satisfaction_2024": 33.0,
    "concession_note": "Paramo ecosystem fragility; 2024 rationing"
  },
  {
    "country": "Colombia",
    "iso3": "COL",
    "region_label": "Other municipal",
    "bws_category_2024": "Medium-High",
    "bws_score_2024": 2.6,
    "bws_category_2030_BAU": "High",
    "bws_score_2030_BAU": 3.2,
    "revenue_share_pct": 2,
    "satisfaction_2024": 33.0,
    "concession_note": "Variable"
  },
  {
    "country": "Other",
    "iso3": "WLD",
    "region_label": "USA / Canada / UAE / Algeria projects",
    "bws_category_2024": "Mixed",
    "bws_score_2024": 2.8,
    "bws_category_2030_BAU": "High",
    "bws_score_2030_BAU": 3.4,
    "revenue_share_pct": 7,
    "satisfaction_2024": "",
    "concession_note": "Project-operation footprint"
  }
],
  coverage: [
  {
    "dp_id": "E1-1",
    "standard": "E1",
    "family": "Environment",
    "disclosure_requirement": "Transition plan",
    "description": "Transition plan for climate change mitigation aligned with the Paris Agreement 1.5C goal",
    "datapoint_type": "narrative",
    "coverage_score": 0.0978119009270315,
    "band": "amber",
    "top_chunk_source": "Corporate context and sustainability framework_2025_ENG.pdf",
    "top_chunk_page": 22,
    "top_chunk_text": "ESRS (CSRD) Código y definición Dueño E3. Water resource sustainability Technological and Infrastructure Innovation S4. Service resilience and reliability O1: Deficiencies in the quality and quantity …"
  },
  {
    "dp_id": "E1-2",
    "standard": "E1",
    "family": "Environment",
    "disclosure_requirement": "Policies",
    "description": "Policies related to climate change mitigation and adaptation",
    "datapoint_type": "narrative",
    "coverage_score": 0.1518904702376131,
    "band": "green",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 16,
    "top_chunk_text": "16Aqualia | Presentación Corporativa | 2025 Phase 3: Material Topics 2025 Material Topics 2025 (16) Material Topics 2024 (15) Water Efficiency, Commitment to Climate Change Mitigation and Adaptation, …"
  },
  {
    "dp_id": "E1-3",
    "standard": "E1",
    "family": "Environment",
    "disclosure_requirement": "Actions",
    "description": "Actions and resources in relation to climate change policies including financial effects",
    "datapoint_type": "semi-narrative",
    "coverage_score": 0.0722659887576717,
    "band": "red",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 16,
    "top_chunk_text": "16Aqualia | Presentación Corporativa | 2025 Phase 3: Material Topics 2025 Material Topics 2025 (16) Material Topics 2024 (15) Water Efficiency, Commitment to Climate Change Mitigation and Adaptation, …"
  },
  {
    "dp_id": "E1-4",
    "standard": "E1",
    "family": "Environment",
    "disclosure_requirement": "Targets",
    "description": "Measurable targets for GHG emission reductions absolute and intensity with base year",
    "datapoint_type": "quantitative",
    "coverage_score": 0.060360137451827,
    "band": "dark_red",
    "top_chunk_source": "Corporate context and sustainability framework_2025_ENG.pdf",
    "top_chunk_page": 12,
    "top_chunk_text": "1. Context Internal Management. Integrated Management System Architecture Aqualia’s corporate-level management model integrates all key strategic elements into a coherent ecosystem that links context …"
  },
  {
    "dp_id": "E1-5",
    "standard": "E1",
    "family": "Environment",
    "disclosure_requirement": "Energy consumption",
    "description": "Energy consumption and mix total MWh by source renewable vs non-renewable",
    "datapoint_type": "quantitative",
    "coverage_score": 0.0746135064105286,
    "band": "red",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 10,
    "top_chunk_text": "10 Review of the Double Materiality Phase 1.1: Contextual Analysis – Key Findings S&P Global Multi & Water Utilities Sector Assessment dimensions: • Environmental (44%): climate strategy, water manage…"
  },
  {
    "dp_id": "E1-6",
    "standard": "E1",
    "family": "Environment",
    "disclosure_requirement": "Gross Scopes 1 2 3 GHG emissions",
    "description": "Gross Scope 1 Scope 2 and Scope 3 GHG emissions tCO2e with methodology",
    "datapoint_type": "quantitative",
    "coverage_score": 0.1055977211558574,
    "band": "amber",
    "top_chunk_source": "Methodology Double Materiality Assessment Review.pdf",
    "top_chunk_page": 5,
    "top_chunk_text": "2. Assessment of Impact Materiality The impacts on the different stakeholder groups may be positive or negative, and current or potential. They are assessed as follows: • Potential impacts: assessed i…"
  },
  {
    "dp_id": "E1-7",
    "standard": "E1",
    "family": "Environment",
    "disclosure_requirement": "GHG removals and mitigation",
    "description": "GHG removals and GHG mitigation projects financed through carbon credits",
    "datapoint_type": "quantitative",
    "coverage_score": 0.0486321978877865,
    "band": "dark_red",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 6,
    "top_chunk_text": "6 Since 2020, several relevant regulations preceding the European Water Resilience Strategy have paved the way: ▪ 2021: Glasgow Declaration for Fair Water Footprints (International) – promotes corpora…"
  },
  {
    "dp_id": "E1-8",
    "standard": "E1",
    "family": "Environment",
    "disclosure_requirement": "Internal carbon pricing",
    "description": "Internal carbon pricing schemes used to support decision making",
    "datapoint_type": "semi-narrative",
    "coverage_score": 0.1064452876926741,
    "band": "green",
    "top_chunk_source": "Corporate context and sustainability framework_2025_ENG.pdf",
    "top_chunk_page": 12,
    "top_chunk_text": "1. Context Internal Management. Integrated Management System Architecture Aqualia’s corporate-level management model integrates all key strategic elements into a coherent ecosystem that links context …"
  },
  {
    "dp_id": "E1-9",
    "standard": "E1",
    "family": "Environment",
    "disclosure_requirement": "Anticipated financial effects",
    "description": "Anticipated financial effects from material physical and transition risks and opportunities",
    "datapoint_type": "quantitative",
    "coverage_score": 0.1483291711551548,
    "band": "green",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 14,
    "top_chunk_text": "Identification of ESRS-Aligned IROs: Risks & Opportunities Based on the list of material topics resulting from the contextual analysis carried out according to the EFRAG-proposed list and in alignment…"
  },
  {
    "dp_id": "E2-1",
    "standard": "E2",
    "family": "Environment",
    "disclosure_requirement": "Pollution policies",
    "description": "Policies related to pollution prevention and control including emerging pollutants",
    "datapoint_type": "narrative",
    "coverage_score": 0.0775720286860161,
    "band": "red",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 6,
    "top_chunk_text": "6 Since 2020, several relevant regulations preceding the European Water Resilience Strategy have paved the way: ▪ 2021: Glasgow Declaration for Fair Water Footprints (International) – promotes corpora…"
  },
  {
    "dp_id": "E2-2",
    "standard": "E2",
    "family": "Environment",
    "disclosure_requirement": "Pollution actions",
    "description": "Actions and resources related to pollution",
    "datapoint_type": "semi-narrative",
    "coverage_score": 0.0448180699320502,
    "band": "dark_red",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 11,
    "top_chunk_text": "11 Phase 1.2: Conclusions from the Competitor Materiality Analysis — Listings To Aqualia’s existing High Risks, additional risks were incorporated due to recurrence among competitors and insights from…"
  },
  {
    "dp_id": "E2-3",
    "standard": "E2",
    "family": "Environment",
    "disclosure_requirement": "Pollution targets",
    "description": "Targets related to pollution reduction",
    "datapoint_type": "quantitative",
    "coverage_score": 0.0493548981070306,
    "band": "dark_red",
    "top_chunk_source": "Aqualia_SR_2023_ES.pdf",
    "top_chunk_page": 33,
    "top_chunk_text": "33 Informe de Sostenibilidad 2023 Total de Iniciativas por meta Metas LE1 LE2 LE3 LE4 LE5 LE6 LE7 Iniciativas Meta 12.4 - 2 - - - - - 2 Meta 12.5 - 2 - - - - - 4 Meta 12.8 5 - - - 2 - - 7 Meta 13.1 - …"
  },
  {
    "dp_id": "E2-4",
    "standard": "E2",
    "family": "Environment",
    "disclosure_requirement": "Pollution emissions",
    "description": "Pollution of air water and soil by type of pollutant and medium",
    "datapoint_type": "quantitative",
    "coverage_score": 0.0376913123653198,
    "band": "dark_red",
    "top_chunk_source": "Methodology Double Materiality Assessment Review.pdf",
    "top_chunk_page": 6,
    "top_chunk_text": "For each impact, a consolidated rating is calculated: • For current impacts, the consolidated rating is equivalent to the severity, calculated as the average of (Scale + Scope + Remediability) / 3, mu…"
  },
  {
    "dp_id": "E2-5",
    "standard": "E2",
    "family": "Environment",
    "disclosure_requirement": "Substances of concern",
    "description": "Substances of concern and substances of very high concern produced used or sold",
    "datapoint_type": "quantitative",
    "coverage_score": 0.0454138618862033,
    "band": "dark_red",
    "top_chunk_source": "Corporate narrative about DM process_Aqualia.pdf",
    "top_chunk_page": 3,
    "top_chunk_text": "aware, connected and aligned organisation, with a more mature map of impacts, risks and opportunities and a reinforced strategic framework. A more dynamic and accurate materiality that strengthens lon…"
  },
  {
    "dp_id": "E3-1",
    "standard": "E3",
    "family": "Environment",
    "disclosure_requirement": "Water marine policies",
    "description": "Policies related to water and marine resources including water stewardship",
    "datapoint_type": "narrative",
    "coverage_score": 0.0924975972529668,
    "band": "amber",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 11,
    "top_chunk_text": "11 Phase 1.2: Conclusions from the Competitor Materiality Analysis — Listings To Aqualia’s existing High Risks, additional risks were incorporated due to recurrence among competitors and insights from…"
  },
  {
    "dp_id": "E3-2",
    "standard": "E3",
    "family": "Environment",
    "disclosure_requirement": "Water actions",
    "description": "Actions and resources related to water and marine resources",
    "datapoint_type": "semi-narrative",
    "coverage_score": 0.0773259998278002,
    "band": "red",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 11,
    "top_chunk_text": "11 Phase 1.2: Conclusions from the Competitor Materiality Analysis — Listings To Aqualia’s existing High Risks, additional risks were incorporated due to recurrence among competitors and insights from…"
  },
  {
    "dp_id": "E3-3",
    "standard": "E3",
    "family": "Environment",
    "disclosure_requirement": "Water targets",
    "description": "Targets related to water and marine resources including water-stressed areas",
    "datapoint_type": "quantitative",
    "coverage_score": 0.0748033092696125,
    "band": "red",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 11,
    "top_chunk_text": "11 Phase 1.2: Conclusions from the Competitor Materiality Analysis — Listings To Aqualia’s existing High Risks, additional risks were incorporated due to recurrence among competitors and insights from…"
  },
  {
    "dp_id": "E3-4",
    "standard": "E3",
    "family": "Environment",
    "disclosure_requirement": "Water consumption",
    "description": "Water consumption total and in water-stressed areas by source",
    "datapoint_type": "quantitative",
    "coverage_score": 0.0551369602352431,
    "band": "dark_red",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 7,
    "top_chunk_text": "7 2025: EU Water Resilience Strategy (European Union) A high-level strategy adopted in June, focused on water security in the face of scarcity and pollution. It sets out an integrated, circular and di…"
  },
  {
    "dp_id": "E3-5",
    "standard": "E3",
    "family": "Environment",
    "disclosure_requirement": "Water financial effects",
    "description": "Anticipated financial effects from water and marine resources material risks and opportunities",
    "datapoint_type": "quantitative",
    "coverage_score": 0.1191714241600427,
    "band": "green",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 14,
    "top_chunk_text": "Identification of ESRS-Aligned IROs: Risks & Opportunities Based on the list of material topics resulting from the contextual analysis carried out according to the EFRAG-proposed list and in alignment…"
  },
  {
    "dp_id": "E4-1",
    "standard": "E4",
    "family": "Environment",
    "disclosure_requirement": "Biodiversity transition plan",
    "description": "Transition plan and consideration of biodiversity and ecosystems in strategy",
    "datapoint_type": "narrative",
    "coverage_score": 0.0809152800445521,
    "band": "red",
    "top_chunk_source": "Aqualia_SR_2024_web.pdf",
    "top_chunk_page": 135,
    "top_chunk_text": "Una organización diversa e inclusiva Nuestra cultura no es solo transformadora y saludable, también es diversa e inclusiva. Hemos conseguido crear espacios de respeto, inclusivos, igualitarios y libre…"
  },
  {
    "dp_id": "E4-2",
    "standard": "E4",
    "family": "Environment",
    "disclosure_requirement": "Biodiversity policies",
    "description": "Policies related to biodiversity and ecosystems",
    "datapoint_type": "narrative",
    "coverage_score": 0.0766147845933248,
    "band": "red",
    "top_chunk_source": "Aqualia_SR_2024_web.pdf",
    "top_chunk_page": 135,
    "top_chunk_text": "Una organización diversa e inclusiva Nuestra cultura no es solo transformadora y saludable, también es diversa e inclusiva. Hemos conseguido crear espacios de respeto, inclusivos, igualitarios y libre…"
  },
  {
    "dp_id": "E4-3",
    "standard": "E4",
    "family": "Environment",
    "disclosure_requirement": "Biodiversity actions",
    "description": "Actions and resources related to biodiversity and ecosystems",
    "datapoint_type": "semi-narrative",
    "coverage_score": 0.0680275611964812,
    "band": "red",
    "top_chunk_source": "Aqualia_SR_2024_web.pdf",
    "top_chunk_page": 135,
    "top_chunk_text": "Una organización diversa e inclusiva Nuestra cultura no es solo transformadora y saludable, también es diversa e inclusiva. Hemos conseguido crear espacios de respeto, inclusivos, igualitarios y libre…"
  },
  {
    "dp_id": "E4-4",
    "standard": "E4",
    "family": "Environment",
    "disclosure_requirement": "Biodiversity targets",
    "description": "Targets related to biodiversity and ecosystems including no net loss commitments",
    "datapoint_type": "quantitative",
    "coverage_score": 0.0738768850713837,
    "band": "red",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 11,
    "top_chunk_text": "11 Phase 1.2: Conclusions from the Competitor Materiality Analysis — Listings To Aqualia’s existing High Risks, additional risks were incorporated due to recurrence among competitors and insights from…"
  },
  {
    "dp_id": "E4-5",
    "standard": "E4",
    "family": "Environment",
    "disclosure_requirement": "Impact metrics biodiversity",
    "description": "Impact metrics related to biodiversity and ecosystems change including land use",
    "datapoint_type": "quantitative",
    "coverage_score": 0.0941802145335215,
    "band": "amber",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 16,
    "top_chunk_text": "16Aqualia | Presentación Corporativa | 2025 Phase 3: Material Topics 2025 Material Topics 2025 (16) Material Topics 2024 (15) Water Efficiency, Commitment to Climate Change Mitigation and Adaptation, …"
  },
  {
    "dp_id": "E4-6",
    "standard": "E4",
    "family": "Environment",
    "disclosure_requirement": "Biodiversity financial effects",
    "description": "Anticipated financial effects from biodiversity and ecosystem risks and opportunities",
    "datapoint_type": "quantitative",
    "coverage_score": 0.1173489817486244,
    "band": "green",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 14,
    "top_chunk_text": "Identification of ESRS-Aligned IROs: Risks & Opportunities Based on the list of material topics resulting from the contextual analysis carried out according to the EFRAG-proposed list and in alignment…"
  },
  {
    "dp_id": "E5-1",
    "standard": "E5",
    "family": "Environment",
    "disclosure_requirement": "Circular economy policies",
    "description": "Policies related to resource use and circular economy",
    "datapoint_type": "narrative",
    "coverage_score": 0.0795815457780765,
    "band": "red",
    "top_chunk_source": "Corporate context and sustainability framework_2025_ENG.pdf",
    "top_chunk_page": 3,
    "top_chunk_text": "1. Context Aqualia. The Water Sector. Competitors The water sector is undergoing a profound transformation, driven by climate urgency, resource scarcity and increasingly stringent regulatory requireme…"
  },
  {
    "dp_id": "E5-2",
    "standard": "E5",
    "family": "Environment",
    "disclosure_requirement": "Circular economy actions",
    "description": "Actions and resources related to resource use and circular economy",
    "datapoint_type": "semi-narrative",
    "coverage_score": 0.0892835327667564,
    "band": "amber",
    "top_chunk_source": "Corporate context and sustainability framework_2025_ENG.pdf",
    "top_chunk_page": 3,
    "top_chunk_text": "1. Context Aqualia. The Water Sector. Competitors The water sector is undergoing a profound transformation, driven by climate urgency, resource scarcity and increasingly stringent regulatory requireme…"
  },
  {
    "dp_id": "E5-3",
    "standard": "E5",
    "family": "Environment",
    "disclosure_requirement": "Circular economy targets",
    "description": "Targets related to resource use and circular economy",
    "datapoint_type": "quantitative",
    "coverage_score": 0.0748680785945559,
    "band": "red",
    "top_chunk_source": "Corporate context and sustainability framework_2025_ENG.pdf",
    "top_chunk_page": 3,
    "top_chunk_text": "1. Context Aqualia. The Water Sector. Competitors The water sector is undergoing a profound transformation, driven by climate urgency, resource scarcity and increasingly stringent regulatory requireme…"
  },
  {
    "dp_id": "E5-4",
    "standard": "E5",
    "family": "Environment",
    "disclosure_requirement": "Resource inflows",
    "description": "Resource inflows including materials by weight or volume and recycled content",
    "datapoint_type": "quantitative",
    "coverage_score": 0.050759626411817,
    "band": "dark_red",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 11,
    "top_chunk_text": "11 Phase 1.2: Conclusions from the Competitor Materiality Analysis — Listings To Aqualia’s existing High Risks, additional risks were incorporated due to recurrence among competitors and insights from…"
  },
  {
    "dp_id": "E5-5",
    "standard": "E5",
    "family": "Environment",
    "disclosure_requirement": "Resource outflows",
    "description": "Resource outflows including products and waste by destination recycling reuse",
    "datapoint_type": "quantitative",
    "coverage_score": 0.0856841084738692,
    "band": "red",
    "top_chunk_source": "Aqualia_SR_2023_ES.pdf",
    "top_chunk_page": 102,
    "top_chunk_text": "102 Informe de Sostenibilidad 2023 4. Planeta: comprometidos con la regeneración Innovación para proteger los ecosistemas y la lucha contra el cambio climático Registro Acrónimo Nombre completo Inicio…"
  },
  {
    "dp_id": "E5-6",
    "standard": "E5",
    "family": "Environment",
    "disclosure_requirement": "Circular financial effects",
    "description": "Anticipated financial effects from resource use and circular economy risks and opportunities",
    "datapoint_type": "quantitative",
    "coverage_score": 0.1226969088454658,
    "band": "green",
    "top_chunk_source": "Methodology Double Materiality Assessment Review.pdf",
    "top_chunk_page": 7,
    "top_chunk_text": "3. Assessment of Financial Materiality Risks and opportunities are assessed on the basis of their probability of occurrence and the potential magnitude of their financial effects in the short, medium …"
  },
  {
    "dp_id": "S1-1",
    "standard": "S1",
    "family": "Social",
    "disclosure_requirement": "Own workforce policies",
    "description": "Policies related to own workforce including health safety D&I human rights",
    "datapoint_type": "narrative",
    "coverage_score": 0.1166876664540708,
    "band": "green",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 11,
    "top_chunk_text": "11 Phase 1.2: Conclusions from the Competitor Materiality Analysis — Listings To Aqualia’s existing High Risks, additional risks were incorporated due to recurrence among competitors and insights from…"
  },
  {
    "dp_id": "S1-2",
    "standard": "S1",
    "family": "Social",
    "disclosure_requirement": "Workforce engagement",
    "description": "Processes for engaging with own workforce and workers representatives",
    "datapoint_type": "semi-narrative",
    "coverage_score": 0.0338614010695748,
    "band": "dark_red",
    "top_chunk_source": "Aqualia_SR_2022_ES.pdf",
    "top_chunk_page": 168,
    "top_chunk_text": "168 Aqualia | Informe de Sostenibilidad 2022 | Tecnología y digitalización para una gestión consciente y eficiente Tecnología al servicio de una plantilla cada vez más conectada y global La apuesta de…"
  },
  {
    "dp_id": "S1-3",
    "standard": "S1",
    "family": "Social",
    "disclosure_requirement": "Workforce remediation",
    "description": "Channels for own workers to raise concerns and processes to remediate negative impacts",
    "datapoint_type": "semi-narrative",
    "coverage_score": 0.0764916154441099,
    "band": "red",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 13,
    "top_chunk_text": "Phase 2: Inclusion of CSRD Nuances, Reformulation of IROs and Value Chain Mapping Identification of ESRS-Aligned IROs: Impacts Impact Identification: This analysis was conducted through desk research,…"
  },
  {
    "dp_id": "S1-4",
    "standard": "S1",
    "family": "Social",
    "disclosure_requirement": "Workforce actions",
    "description": "Actions and resources for own workforce including training D&I",
    "datapoint_type": "semi-narrative",
    "coverage_score": 0.0444281906570496,
    "band": "dark_red",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 11,
    "top_chunk_text": "11 Phase 1.2: Conclusions from the Competitor Materiality Analysis — Listings To Aqualia’s existing High Risks, additional risks were incorporated due to recurrence among competitors and insights from…"
  },
  {
    "dp_id": "S1-5",
    "standard": "S1",
    "family": "Social",
    "disclosure_requirement": "Workforce targets",
    "description": "Targets related to managing material impacts on own workforce",
    "datapoint_type": "quantitative",
    "coverage_score": 0.0523067312490368,
    "band": "dark_red",
    "top_chunk_source": "Methodology Double Materiality Assessment Review.pdf",
    "top_chunk_page": 3,
    "top_chunk_text": "1. Context analysis AQUALIA 2025: Double Materiality Assessment Review In June 2025, Aqualia decided to conduct a review of its 2024 Double Materiality Assessment in order to reformulate its material …"
  },
  {
    "dp_id": "S1-6",
    "standard": "S1",
    "family": "Social",
    "disclosure_requirement": "Workforce characteristics",
    "description": "Characteristics of own workforce by gender country contract employment type",
    "datapoint_type": "quantitative",
    "coverage_score": 0.0359094457711642,
    "band": "dark_red",
    "top_chunk_source": "Aqualia_SR_2022_ES.pdf",
    "top_chunk_page": 168,
    "top_chunk_text": "168 Aqualia | Informe de Sostenibilidad 2022 | Tecnología y digitalización para una gestión consciente y eficiente Tecnología al servicio de una plantilla cada vez más conectada y global La apuesta de…"
  },
  {
    "dp_id": "S1-7",
    "standard": "S1",
    "family": "Social",
    "disclosure_requirement": "Non-employees",
    "description": "Characteristics of non-employees in own workforce contractors agency",
    "datapoint_type": "quantitative",
    "coverage_score": 0.052906853430023,
    "band": "dark_red",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 11,
    "top_chunk_text": "11 Phase 1.2: Conclusions from the Competitor Materiality Analysis — Listings To Aqualia’s existing High Risks, additional risks were incorporated due to recurrence among competitors and insights from…"
  },
  {
    "dp_id": "S1-14",
    "standard": "S1",
    "family": "Social",
    "disclosure_requirement": "Health and safety",
    "description": "Health and safety metrics coverage fatalities recordable injuries ill health rates",
    "datapoint_type": "quantitative",
    "coverage_score": 0.1401880183120558,
    "band": "green",
    "top_chunk_source": "Aqualia_SR_2025_ES.pdf",
    "top_chunk_page": 84,
    "top_chunk_text": "84 Informe de Sostenibilidad Aqualia 2025 Mensaje del CEO Hitos 2025 Somos Aqualia Estrategia Información ambiental Información social Información de gobernanza Anexos Participaciones sobre salud y se…"
  },
  {
    "dp_id": "S1-16",
    "standard": "S1",
    "family": "Social",
    "disclosure_requirement": "Remuneration gender pay",
    "description": "Remuneration metrics including gender pay gap and total remuneration ratio",
    "datapoint_type": "quantitative",
    "coverage_score": 0.0461472274922345,
    "band": "dark_red",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 11,
    "top_chunk_text": "11 Phase 1.2: Conclusions from the Competitor Materiality Analysis — Listings To Aqualia’s existing High Risks, additional risks were incorporated due to recurrence among competitors and insights from…"
  },
  {
    "dp_id": "S1-17",
    "standard": "S1",
    "family": "Social",
    "disclosure_requirement": "Discrimination incidents",
    "description": "Incidents of discrimination and complaints mechanisms",
    "datapoint_type": "quantitative",
    "coverage_score": 0.0394137019231848,
    "band": "dark_red",
    "top_chunk_source": "Corporate context and sustainability framework_2025_ENG.pdf",
    "top_chunk_page": 12,
    "top_chunk_text": "1. Context Internal Management. Integrated Management System Architecture Aqualia’s corporate-level management model integrates all key strategic elements into a coherent ecosystem that links context …"
  },
  {
    "dp_id": "S2-1",
    "standard": "S2",
    "family": "Social",
    "disclosure_requirement": "Value chain workers policies",
    "description": "Policies related to value chain workers including human rights due diligence",
    "datapoint_type": "narrative",
    "coverage_score": 0.1041676069716111,
    "band": "amber",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 11,
    "top_chunk_text": "11 Phase 1.2: Conclusions from the Competitor Materiality Analysis — Listings To Aqualia’s existing High Risks, additional risks were incorporated due to recurrence among competitors and insights from…"
  },
  {
    "dp_id": "S2-2",
    "standard": "S2",
    "family": "Social",
    "disclosure_requirement": "Value chain workers engagement",
    "description": "Processes for engaging with value chain workers",
    "datapoint_type": "semi-narrative",
    "coverage_score": 0.1058096460581957,
    "band": "green",
    "top_chunk_source": "Corporate context and sustainability framework_2025_ENG.pdf",
    "top_chunk_page": 1,
    "top_chunk_text": "Corporate Context and Sustainability Framework Sustainability and Innovation Deparment January 2026 Index 1. Context 2. Stakeholders 3. Value Chain 4. Double Materiality Assessment…"
  },
  {
    "dp_id": "S2-3",
    "standard": "S2",
    "family": "Social",
    "disclosure_requirement": "Value chain workers remediation",
    "description": "Channels for value chain workers to raise concerns",
    "datapoint_type": "semi-narrative",
    "coverage_score": 0.0900160377402823,
    "band": "amber",
    "top_chunk_source": "Corporate context and sustainability framework_2025_ENG.pdf",
    "top_chunk_page": 1,
    "top_chunk_text": "Corporate Context and Sustainability Framework Sustainability and Innovation Deparment January 2026 Index 1. Context 2. Stakeholders 3. Value Chain 4. Double Materiality Assessment…"
  },
  {
    "dp_id": "S2-4",
    "standard": "S2",
    "family": "Social",
    "disclosure_requirement": "Value chain workers actions",
    "description": "Actions and resources for value chain workers",
    "datapoint_type": "semi-narrative",
    "coverage_score": 0.0864604357538206,
    "band": "amber",
    "top_chunk_source": "Corporate context and sustainability framework_2025_ENG.pdf",
    "top_chunk_page": 1,
    "top_chunk_text": "Corporate Context and Sustainability Framework Sustainability and Innovation Deparment January 2026 Index 1. Context 2. Stakeholders 3. Value Chain 4. Double Materiality Assessment…"
  },
  {
    "dp_id": "S2-5",
    "standard": "S2",
    "family": "Social",
    "disclosure_requirement": "Value chain workers targets",
    "description": "Targets related to managing material impacts on value chain workers",
    "datapoint_type": "quantitative",
    "coverage_score": 0.0920789138117379,
    "band": "amber",
    "top_chunk_source": "Corporate context and sustainability framework_2025_ENG.pdf",
    "top_chunk_page": 1,
    "top_chunk_text": "Corporate Context and Sustainability Framework Sustainability and Innovation Deparment January 2026 Index 1. Context 2. Stakeholders 3. Value Chain 4. Double Materiality Assessment…"
  },
  {
    "dp_id": "S3-1",
    "standard": "S3",
    "family": "Social",
    "disclosure_requirement": "Affected communities policies",
    "description": "Policies related to affected communities including Indigenous Peoples",
    "datapoint_type": "narrative",
    "coverage_score": 0.0595776177208475,
    "band": "dark_red",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 11,
    "top_chunk_text": "11 Phase 1.2: Conclusions from the Competitor Materiality Analysis — Listings To Aqualia’s existing High Risks, additional risks were incorporated due to recurrence among competitors and insights from…"
  },
  {
    "dp_id": "S3-2",
    "standard": "S3",
    "family": "Social",
    "disclosure_requirement": "Community engagement",
    "description": "Processes for engaging with affected communities",
    "datapoint_type": "semi-narrative",
    "coverage_score": 0.0542880718161365,
    "band": "dark_red",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 11,
    "top_chunk_text": "11 Phase 1.2: Conclusions from the Competitor Materiality Analysis — Listings To Aqualia’s existing High Risks, additional risks were incorporated due to recurrence among competitors and insights from…"
  },
  {
    "dp_id": "S3-3",
    "standard": "S3",
    "family": "Social",
    "disclosure_requirement": "Community remediation",
    "description": "Channels for affected communities to raise concerns and access to remedy",
    "datapoint_type": "semi-narrative",
    "coverage_score": 0.0598308946881358,
    "band": "dark_red",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 11,
    "top_chunk_text": "11 Phase 1.2: Conclusions from the Competitor Materiality Analysis — Listings To Aqualia’s existing High Risks, additional risks were incorporated due to recurrence among competitors and insights from…"
  },
  {
    "dp_id": "S3-4",
    "standard": "S3",
    "family": "Social",
    "disclosure_requirement": "Community actions",
    "description": "Actions and resources to address material impacts on affected communities",
    "datapoint_type": "semi-narrative",
    "coverage_score": 0.058595962808314,
    "band": "dark_red",
    "top_chunk_source": "Methodology Double Materiality Assessment Review.pdf",
    "top_chunk_page": 3,
    "top_chunk_text": "1. Context analysis AQUALIA 2025: Double Materiality Assessment Review In June 2025, Aqualia decided to conduct a review of its 2024 Double Materiality Assessment in order to reformulate its material …"
  },
  {
    "dp_id": "S3-5",
    "standard": "S3",
    "family": "Social",
    "disclosure_requirement": "Community targets",
    "description": "Targets related to managing material impacts on affected communities",
    "datapoint_type": "quantitative",
    "coverage_score": 0.0613730951268502,
    "band": "dark_red",
    "top_chunk_source": "Methodology Double Materiality Assessment Review.pdf",
    "top_chunk_page": 3,
    "top_chunk_text": "1. Context analysis AQUALIA 2025: Double Materiality Assessment Review In June 2025, Aqualia decided to conduct a review of its 2024 Double Materiality Assessment in order to reformulate its material …"
  },
  {
    "dp_id": "S4-1",
    "standard": "S4",
    "family": "Social",
    "disclosure_requirement": "Consumer policies",
    "description": "Policies related to consumers and end users including privacy service quality access",
    "datapoint_type": "narrative",
    "coverage_score": 0.1024191642755601,
    "band": "amber",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 11,
    "top_chunk_text": "11 Phase 1.2: Conclusions from the Competitor Materiality Analysis — Listings To Aqualia’s existing High Risks, additional risks were incorporated due to recurrence among competitors and insights from…"
  },
  {
    "dp_id": "S4-2",
    "standard": "S4",
    "family": "Social",
    "disclosure_requirement": "Consumer engagement",
    "description": "Processes for engaging with consumers and end users",
    "datapoint_type": "semi-narrative",
    "coverage_score": 0.0458587923313274,
    "band": "dark_red",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 11,
    "top_chunk_text": "11 Phase 1.2: Conclusions from the Competitor Materiality Analysis — Listings To Aqualia’s existing High Risks, additional risks were incorporated due to recurrence among competitors and insights from…"
  },
  {
    "dp_id": "S4-3",
    "standard": "S4",
    "family": "Social",
    "disclosure_requirement": "Consumer remediation",
    "description": "Channels for consumers to raise concerns and complaint handling",
    "datapoint_type": "semi-narrative",
    "coverage_score": 0.0433272155600926,
    "band": "dark_red",
    "top_chunk_source": "Corporate context and sustainability framework_2025_ENG.pdf",
    "top_chunk_page": 14,
    "top_chunk_text": "1. Context Global Customer Satisfaction Results 2024 The detailed analysis of customer satisfaction surveys by country reveals differentiated patterns that reflect the particular characteristics of ea…"
  },
  {
    "dp_id": "S4-4",
    "standard": "S4",
    "family": "Social",
    "disclosure_requirement": "Consumer actions",
    "description": "Actions and resources to address consumer impacts including service continuity",
    "datapoint_type": "semi-narrative",
    "coverage_score": 0.0593435125311469,
    "band": "dark_red",
    "top_chunk_source": "Corporate context and sustainability framework_2025_ENG.pdf",
    "top_chunk_page": 14,
    "top_chunk_text": "1. Context Global Customer Satisfaction Results 2024 The detailed analysis of customer satisfaction surveys by country reveals differentiated patterns that reflect the particular characteristics of ea…"
  },
  {
    "dp_id": "S4-5",
    "standard": "S4",
    "family": "Social",
    "disclosure_requirement": "Consumer targets",
    "description": "Targets related to managing material impacts on consumers and end users",
    "datapoint_type": "quantitative",
    "coverage_score": 0.061353250622106,
    "band": "dark_red",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 11,
    "top_chunk_text": "11 Phase 1.2: Conclusions from the Competitor Materiality Analysis — Listings To Aqualia’s existing High Risks, additional risks were incorporated due to recurrence among competitors and insights from…"
  },
  {
    "dp_id": "G1-1",
    "standard": "G1",
    "family": "Governance",
    "disclosure_requirement": "Business conduct governance",
    "description": "Role of the administrative management and supervisory bodies in business conduct",
    "datapoint_type": "narrative",
    "coverage_score": 0.0872242404201879,
    "band": "amber",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 11,
    "top_chunk_text": "11 Phase 1.2: Conclusions from the Competitor Materiality Analysis — Listings To Aqualia’s existing High Risks, additional risks were incorporated due to recurrence among competitors and insights from…"
  },
  {
    "dp_id": "G1-2",
    "standard": "G1",
    "family": "Governance",
    "disclosure_requirement": "Business conduct policies",
    "description": "Policies on business conduct matters including anti-corruption and anti-bribery",
    "datapoint_type": "narrative",
    "coverage_score": 0.1039945688548402,
    "band": "amber",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 11,
    "top_chunk_text": "11 Phase 1.2: Conclusions from the Competitor Materiality Analysis — Listings To Aqualia’s existing High Risks, additional risks were incorporated due to recurrence among competitors and insights from…"
  },
  {
    "dp_id": "G1-3",
    "standard": "G1",
    "family": "Governance",
    "disclosure_requirement": "Corruption prevention",
    "description": "Prevention and detection of corruption and bribery including training coverage",
    "datapoint_type": "semi-narrative",
    "coverage_score": 0.0604979588159701,
    "band": "dark_red",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 11,
    "top_chunk_text": "11 Phase 1.2: Conclusions from the Competitor Materiality Analysis — Listings To Aqualia’s existing High Risks, additional risks were incorporated due to recurrence among competitors and insights from…"
  },
  {
    "dp_id": "G1-4",
    "standard": "G1",
    "family": "Governance",
    "disclosure_requirement": "Corruption incidents",
    "description": "Confirmed incidents of corruption or bribery and public cases",
    "datapoint_type": "quantitative",
    "coverage_score": 0.0617038082508412,
    "band": "dark_red",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 11,
    "top_chunk_text": "11 Phase 1.2: Conclusions from the Competitor Materiality Analysis — Listings To Aqualia’s existing High Risks, additional risks were incorporated due to recurrence among competitors and insights from…"
  },
  {
    "dp_id": "G1-5",
    "standard": "G1",
    "family": "Governance",
    "disclosure_requirement": "Political engagement",
    "description": "Political influence and lobbying activities including contributions",
    "datapoint_type": "quantitative",
    "coverage_score": 0.063967685451733,
    "band": "dark_red",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 11,
    "top_chunk_text": "11 Phase 1.2: Conclusions from the Competitor Materiality Analysis — Listings To Aqualia’s existing High Risks, additional risks were incorporated due to recurrence among competitors and insights from…"
  },
  {
    "dp_id": "G1-6",
    "standard": "G1",
    "family": "Governance",
    "disclosure_requirement": "Payment practices",
    "description": "Payment practices to suppliers including average payment days",
    "datapoint_type": "quantitative",
    "coverage_score": 0.0829071422331714,
    "band": "red",
    "top_chunk_source": "Aqualia_SR_2023_ES.pdf",
    "top_chunk_page": 73,
    "top_chunk_text": "73 3. Impulsamos nuestra versión más transformadora y sostenible Comunicación transparente Informe de Sostenibilidad 2023 En 2023 con el objetivo de avanzar más en la dirección marcada por la directiv…"
  },
  {
    "dp_id": "G1-7",
    "standard": "G1",
    "family": "Governance",
    "disclosure_requirement": "Business ethics culture",
    "description": "Business ethics culture including whistleblower protection mechanisms",
    "datapoint_type": "semi-narrative",
    "coverage_score": 0.0796931356898777,
    "band": "red",
    "top_chunk_source": "v2_VF_Aqualia Informe final Revision Doble Materialidad 2025_ENG.pdf",
    "top_chunk_page": 11,
    "top_chunk_text": "11 Phase 1.2: Conclusions from the Competitor Materiality Analysis — Listings To Aqualia’s existing High Risks, additional risks were incorporated due to recurrence among competitors and insights from…"
  },
  {
    "dp_id": "G1-8",
    "standard": "G1",
    "family": "Governance",
    "disclosure_requirement": "Data governance cyber",
    "description": "Data governance and cybersecurity practices for business critical systems",
    "datapoint_type": "narrative",
    "coverage_score": 0.0949313354304626,
    "band": "amber",
    "top_chunk_source": "Corporate context and sustainability framework_2025_ENG.pdf",
    "top_chunk_page": 4,
    "top_chunk_text": "1. Context The Water Sector. Competitors. Best Practices The analysis of best practices within the sector reveals a set of technological and operational capabilities that define excellence in the mana…"
  },
  {
    "dp_id": "AQ-DIG-1",
    "standard": "AQ",
    "family": "Sector",
    "disclosure_requirement": "Digital twin deployment",
    "description": "Deployment of digital twin of the water network and coverage percentage",
    "datapoint_type": "quantitative",
    "coverage_score": 0.0761966032943407,
    "band": "red",
    "top_chunk_source": "Corporate context and sustainability framework_2025_ENG.pdf",
    "top_chunk_page": 5,
    "top_chunk_text": "1. Context The Water Sector. Competitors. Strengths and Weaknesses The SWOT analysis of the main competitors makes it possible to identify competitive advantages and common areas of vulnerability with…"
  },
  {
    "dp_id": "AQ-DIG-2",
    "standard": "AQ",
    "family": "Sector",
    "disclosure_requirement": "AI for operations",
    "description": "Use of AI for demand prediction leak detection predictive maintenance",
    "datapoint_type": "semi-narrative",
    "coverage_score": 0.1224158533597488,
    "band": "green",
    "top_chunk_source": "Corporate context and sustainability framework_2025_ENG.pdf",
    "top_chunk_page": 15,
    "top_chunk_text": "Aqualia faces an increasingly complex environment that requires simultaneous responses across multiple fronts: technical, sustainability-related and commercial. These challenges are not isolated obsta…"
  },
  {
    "dp_id": "AQ-CYB-1",
    "standard": "AQ",
    "family": "Sector",
    "disclosure_requirement": "Cyber incident response plan",
    "description": "Cybersecurity incident response plan testing frequency and OT/IT scope",
    "datapoint_type": "semi-narrative",
    "coverage_score": 0.0763782599073937,
    "band": "red",
    "top_chunk_source": "Corporate context and sustainability framework_2025_ENG.pdf",
    "top_chunk_page": 19,
    "top_chunk_text": "4. Double Materiality Review CSRD Material Topics and Integrated Risk Management Reformulation of Material Topics in line with CSRD Based on the 12 major ESG themes identified through the contextual a…"
  },
  {
    "dp_id": "AQ-CYB-2",
    "standard": "AQ",
    "family": "Sector",
    "disclosure_requirement": "Cyber investment",
    "description": "Annual investment in cybersecurity and OT/IT security",
    "datapoint_type": "quantitative",
    "coverage_score": 0.0601238440230301,
    "band": "dark_red",
    "top_chunk_source": "Aqualia_SR_2023_ES.pdf",
    "top_chunk_page": 136,
    "top_chunk_text": "136 Informe de Sostenibilidad 2023 6. Tecnología y digitalización para un servicio excelente Hacia una gestión del agua basada en datos en tiempo real Gestión inteligente e integrada Tratamiento y pot…"
  },
  {
    "dp_id": "AQ-FIN-1",
    "standard": "AQ",
    "family": "Sector",
    "disclosure_requirement": "Green bond issuance",
    "description": "Volume and coverage of green sustainability-linked and social bonds",
    "datapoint_type": "quantitative",
    "coverage_score": 0.0859843143725879,
    "band": "red",
    "top_chunk_source": "Corporate context and sustainability framework_2025_ENG.pdf",
    "top_chunk_page": 15,
    "top_chunk_text": "Aqualia faces an increasingly complex environment that requires simultaneous responses across multiple fronts: technical, sustainability-related and commercial. These challenges are not isolated obsta…"
  },
  {
    "dp_id": "AQ-FIN-2",
    "standard": "AQ",
    "family": "Sector",
    "disclosure_requirement": "EU Taxonomy alignment",
    "description": "EU Taxonomy eligible and aligned revenue CAPEX and OPEX",
    "datapoint_type": "quantitative",
    "coverage_score": 0.1277705834580917,
    "band": "green",
    "top_chunk_source": "Aqualia_SR_2024_web.pdf",
    "top_chunk_page": 103,
    "top_chunk_text": "alineados por taxonomía (numerador), dividida por la facturación total de la empresa, CapEx y OpEx definido por taxonomía (denominador). • Facturación–volumen de negocio: proporción de facturación-vol…"
  },
  {
    "dp_id": "AQ-FIN-3",
    "standard": "AQ",
    "family": "Sector",
    "disclosure_requirement": "TNFD alignment",
    "description": "TNFD LEAP assessment coverage and nature-related financial disclosure",
    "datapoint_type": "semi-narrative",
    "coverage_score": 0.1491366208761258,
    "band": "green",
    "top_chunk_source": "Corporate narrative about DM process_Aqualia.pdf",
    "top_chunk_page": 1,
    "top_chunk_text": "Aqualia’s Double Materiality Review: Turning Sustainability into a Strategic Engine for Long‑Term Value Aqualia’s vision: growth, financial strength and positive impact At Aqualia, growth, financial s…"
  },
  {
    "dp_id": "AQ-OPS-1",
    "standard": "AQ",
    "family": "Sector",
    "disclosure_requirement": "Non-revenue water",
    "description": "Non-revenue water NRW percentage by concession and trend",
    "datapoint_type": "quantitative",
    "coverage_score": 0.0941390350320102,
    "band": "amber",
    "top_chunk_source": "Corporate context and sustainability framework_2025_ENG.pdf",
    "top_chunk_page": 15,
    "top_chunk_text": "Aqualia faces an increasingly complex environment that requires simultaneous responses across multiple fronts: technical, sustainability-related and commercial. These challenges are not isolated obsta…"
  },
  {
    "dp_id": "AQ-OPS-2",
    "standard": "AQ",
    "family": "Sector",
    "disclosure_requirement": "Energy intensity",
    "description": "Energy intensity kWh per m3 of water treated and distributed",
    "datapoint_type": "quantitative",
    "coverage_score": 0.0663681666327934,
    "band": "red",
    "top_chunk_source": "Aqualia_SR_2024_web.pdf",
    "top_chunk_page": 91,
    "top_chunk_text": "ACTUACIÓN DESTACADA EN 2024 Hub Reusa En el contexto de las nuevas exigencias legales, el Hub Reusa se enfoca en la regeneración y reutilización avanzadas de aguas residuales urbanas. Se trata de una …"
  },
  {
    "dp_id": "AQ-OPS-3",
    "standard": "AQ",
    "family": "Sector",
    "disclosure_requirement": "Water reuse percentage",
    "description": "Percentage of treated wastewater reused and target pathway",
    "datapoint_type": "quantitative",
    "coverage_score": 0.0491508833571621,
    "band": "dark_red",
    "top_chunk_source": "Corporate context and sustainability framework_2025_ENG.pdf",
    "top_chunk_page": 15,
    "top_chunk_text": "Aqualia faces an increasingly complex environment that requires simultaneous responses across multiple fronts: technical, sustainability-related and commercial. These challenges are not isolated obsta…"
  },
  {
    "dp_id": "AQ-OPS-4",
    "standard": "AQ",
    "family": "Sector",
    "disclosure_requirement": "Sludge valorisation",
    "description": "Sludge valorisation pathways and percentage treated",
    "datapoint_type": "quantitative",
    "coverage_score": 0.0524166066757827,
    "band": "dark_red",
    "top_chunk_source": "Corporate context and sustainability framework_2025_ENG.pdf",
    "top_chunk_page": 15,
    "top_chunk_text": "Aqualia faces an increasingly complex environment that requires simultaneous responses across multiple fronts: technical, sustainability-related and commercial. These challenges are not isolated obsta…"
  }
],
  tornado: [
  {
    "topic": "T1 Water Resilience & Equitable Access",
    "axis": "Impact",
    "input": "E3-deplete.scale",
    "base": 5,
    "swing": 0.0503402080192851,
    "low": -0.0503624365323012,
    "high": -2.222851301603157e-05,
    "abs_swing": 0.0503402080192851
  },
  {
    "topic": "T1 Water Resilience & Equitable Access",
    "axis": "Impact",
    "input": "E3-deplete.prob",
    "base": 5,
    "swing": -0.0003232457841146,
    "low": -0.0003533025346054,
    "high": -0.0006765483187201,
    "abs_swing": 0.0003232457841146
  },
  {
    "topic": "T1 Water Resilience & Equitable Access",
    "axis": "Impact",
    "input": "E3-quality.scale",
    "base": 4,
    "swing": 0.1137589610923592,
    "low": -0.0604344291168792,
    "high": 0.05332453197548,
    "abs_swing": 0.1137589610923592
  },
  {
    "topic": "T1 Water Resilience & Equitable Access",
    "axis": "Impact",
    "input": "E3-quality.prob",
    "base": 4,
    "swing": 0.0006333486935559,
    "low": 0.0007251835001897,
    "high": 0.0013585321937457,
    "abs_swing": 0.0006333486935559
  },
  {
    "topic": "T1 Water Resilience & Equitable Access",
    "axis": "Impact",
    "input": "E1-adaptation.scale",
    "base": 4,
    "swing": 0.0578030305713705,
    "low": -0.0272357818251292,
    "high": 0.0305672487462413,
    "abs_swing": 0.0578030305713705
  },
  {
    "topic": "T1 Water Resilience & Equitable Access",
    "axis": "Impact",
    "input": "E1-adaptation.prob",
    "base": 4,
    "swing": 0.1590984356900295,
    "low": -0.0375497902200301,
    "high": 0.1215486454699994,
    "abs_swing": 0.1590984356900295
  },
  {
    "topic": "T1 Water Resilience & Equitable Access",
    "axis": "Impact",
    "input": "E1-emissions.scale",
    "base": 3,
    "swing": 0.0741221081430603,
    "low": -0.0188197581122206,
    "high": 0.0553023500308396,
    "abs_swing": 0.0741221081430603
  },
  {
    "topic": "T1 Water Resilience & Equitable Access",
    "axis": "Impact",
    "input": "E1-emissions.prob",
    "base": 4,
    "swing": 0.0013575927495947,
    "low": -5.933559069903893e-05,
    "high": 0.0012982571588957,
    "abs_swing": 0.0013575927495947
  },
  {
    "topic": "T1 Water Resilience & Equitable Access",
    "axis": "Impact",
    "input": "S4-continuity.scale",
    "base": 5,
    "swing": 0.0078046916911649,
    "low": -0.0075510791080595,
    "high": 0.0002536125831054,
    "abs_swing": 0.0078046916911649
  },
  {
    "topic": "T1 Water Resilience & Equitable Access",
    "axis": "Impact",
    "input": "S4-continuity.prob",
    "base": 4,
    "swing": 0.0831035998237847,
    "low": -0.0080103554334791,
    "high": 0.0750932443903056,
    "abs_swing": 0.0831035998237847
  },
  {
    "topic": "T1 Water Resilience & Equitable Access",
    "axis": "Impact",
    "input": "S3-equity-access.scale",
    "base": 4,
    "swing": 0.0612382959913504,
    "low": -0.020658855834382,
    "high": 0.0405794401569683,
    "abs_swing": 0.0612382959913504
  },
  {
    "topic": "T1 Water Resilience & Equitable Access",
    "axis": "Impact",
    "input": "S3-equity-access.prob",
    "base": 5,
    "swing": 0.001167721590324,
    "low": -0.0011227692379081,
    "high": 4.4952352415972285e-05,
    "abs_swing": 0.001167721590324
  },
  {
    "topic": "T1 Water Resilience & Equitable Access",
    "axis": "Financial",
    "input": "R-stress-revenue.mag",
    "base": 4,
    "swing": 0.2087388640276195,
    "low": -0.1388117310768004,
    "high": 0.0699271329508191,
    "abs_swing": 0.2087388640276195
  },
  {
    "topic": "T1 Water Resilience & Equitable Access",
    "axis": "Financial",
    "input": "R-capex-uwwtd.mag",
    "base": 5,
    "swing": 0.1186787249346013,
    "low": -0.1199914713366392,
    "high": -0.0013127464020379,
    "abs_swing": 0.1186787249346013
  },
  {
    "topic": "T1 Water Resilience & Equitable Access",
    "axis": "Financial",
    "input": "R-fines-wfd.mag",
    "base": 3,
    "swing": 0.0961477274375264,
    "low": -0.0224181558460014,
    "high": 0.0737295715915249,
    "abs_swing": 0.0961477274375264
  },
  {
    "topic": "T1 Water Resilience & Equitable Access",
    "axis": "Financial",
    "input": "O-reuse-market.mag",
    "base": 3,
    "swing": 0.1316864730587492,
    "low": -0.0354908481736275,
    "high": 0.0961956248851216,
    "abs_swing": 0.1316864730587492
  },
  {
    "topic": "T1 Water Resilience & Equitable Access",
    "axis": "Financial",
    "input": "O-nature-credits.mag",
    "base": 2,
    "swing": 0.0039447056683585,
    "low": -0.0021013343276901,
    "high": 0.0018433713406684,
    "abs_swing": 0.0039447056683585
  },
  {
    "topic": "T2 Digital & Cyber Infrastructure",
    "axis": "Impact",
    "input": "Tech-pace.scale",
    "base": 3,
    "swing": 0.1441331505022023,
    "low": -0.0703883631251418,
    "high": 0.0737447873770604,
    "abs_swing": 0.1441331505022023
  },
  {
    "topic": "T2 Digital & Cyber Infrastructure",
    "axis": "Impact",
    "input": "Tech-pace.prob",
    "base": 4,
    "swing": 0.2791168504639998,
    "low": -0.1409883926173085,
    "high": 0.1381284578466912,
    "abs_swing": 0.2791168504639998
  },
  {
    "topic": "T2 Digital & Cyber Infrastructure",
    "axis": "Impact",
    "input": "Dig-adoption.scale",
    "base": 3,
    "swing": 0.1838437989214232,
    "low": -0.0917575953909959,
    "high": 0.0920862035304272,
    "abs_swing": 0.1838437989214232
  },
  {
    "topic": "T2 Digital & Cyber Infrastructure",
    "axis": "Impact",
    "input": "Dig-adoption.prob",
    "base": 4,
    "swing": 7.564558293715606e-05,
    "low": -0.0005929505082908,
    "high": -0.0005173049253537,
    "abs_swing": 7.564558293715606e-05
  },
  {
    "topic": "T2 Digital & Cyber Infrastructure",
    "axis": "Impact",
    "input": "Dig-data-gov.scale",
    "base": 3,
    "swing": 0.1224696253199666,
    "low": -0.0580174662805759,
    "high": 0.0644521590393907,
    "abs_swing": 0.1224696253199666
  },
  {
    "topic": "T2 Digital & Cyber Infrastructure",
    "axis": "Impact",
    "input": "Dig-data-gov.prob",
    "base": 4,
    "swing": 0.20264771160257,
    "low": -0.0831260524129895,
    "high": 0.1195216591895804,
    "abs_swing": 0.20264771160257
  },
  {
    "topic": "T2 Digital & Cyber Infrastructure",
    "axis": "Impact",
    "input": "Cyber-incident.scale",
    "base": 4,
    "swing": 0.0096439028889556,
    "low": -0.0038411607582347,
    "high": 0.0058027421307209,
    "abs_swing": 0.0096439028889556
  },
  {
    "topic": "T2 Digital & Cyber Infrastructure",
    "axis": "Impact",
    "input": "Cyber-incident.prob",
    "base": 3,
    "swing": 0.0909536006745312,
    "low": -0.0051001377464041,
    "high": 0.0858534629281271,
    "abs_swing": 0.0909536006745312
  },
  {
    "topic": "T2 Digital & Cyber Infrastructure",
    "axis": "Impact",
    "input": "Cyber-OT-IT.scale",
    "base": 4,
    "swing": 0.0115575290615543,
    "low": -0.0047157589001236,
    "high": 0.0068417701614307,
    "abs_swing": 0.0115575290615543
  },
  {
    "topic": "T2 Digital & Cyber Infrastructure",
    "axis": "Impact",
    "input": "Cyber-OT-IT.prob",
    "base": 3,
    "swing": 0.0856213466767381,
    "low": -0.0035785663628824,
    "high": 0.0820427803138557,
    "abs_swing": 0.0856213466767381
  },
  {
    "topic": "T2 Digital & Cyber Infrastructure",
    "axis": "Financial",
    "input": "R-cyber-incident.mag",
    "base": 3,
    "swing": 0.0831623576528337,
    "low": -0.0419058767938715,
    "high": 0.0412564808589621,
    "abs_swing": 0.0831623576528337
  },
  {
    "topic": "T2 Digital & Cyber Infrastructure",
    "axis": "Financial",
    "input": "R-nis2-gdpr.mag",
    "base": 3,
    "swing": 0.0956103503825085,
    "low": -0.0185222075602689,
    "high": 0.0770881428222396,
    "abs_swing": 0.0956103503825085
  },
  {
    "topic": "T2 Digital & Cyber Infrastructure",
    "axis": "Financial",
    "input": "R-digital-capex.mag",
    "base": 4,
    "swing": 0.2187698220233374,
    "low": -0.0991732417898334,
    "high": 0.1195965802335039,
    "abs_swing": 0.2187698220233374
  },
  {
    "topic": "T2 Digital & Cyber Infrastructure",
    "axis": "Financial",
    "input": "O-tender-uplift.mag",
    "base": 3,
    "swing": 0.2521483179728441,
    "low": -0.1077370744628369,
    "high": 0.1444112435100071,
    "abs_swing": 0.2521483179728441
  },
  {
    "topic": "T2 Digital & Cyber Infrastructure",
    "axis": "Financial",
    "input": "O-pred-maint-opex.mag",
    "base": 2,
    "swing": 0.0342418500661181,
    "low": -0.0011858534218025,
    "high": 0.0330559966443155,
    "abs_swing": 0.0342418500661181
  },
  {
    "topic": "T3 Green Finance & Integrity",
    "axis": "Impact",
    "input": "Compl-CSRD.scale",
    "base": 3,
    "swing": 0.1858674321630227,
    "low": -0.0913112250875989,
    "high": 0.0945562070754237,
    "abs_swing": 0.1858674321630227
  },
  {
    "topic": "T3 Green Finance & Integrity",
    "axis": "Impact",
    "input": "Compl-CSRD.prob",
    "base": 5,
    "swing": 0.0002571100095516,
    "low": 0.0018407052940259,
    "high": 0.0020978153035775,
    "abs_swing": 0.0002571100095516
  },
  {
    "topic": "T3 Green Finance & Integrity",
    "axis": "Impact",
    "input": "Compl-CSDDD.scale",
    "base": 3,
    "swing": 0.1379133803730634,
    "low": -0.0672085679197231,
    "high": 0.0707048124533402,
    "abs_swing": 0.1379133803730634
  },
  {
    "topic": "T3 Green Finance & Integrity",
    "axis": "Impact",
    "input": "Compl-CSDDD.prob",
    "base": 4,
    "swing": 0.2956848520251895,
    "low": -0.1512916131262742,
    "high": 0.1443932388989153,
    "abs_swing": 0.2956848520251895
  },
  {
    "topic": "T3 Green Finance & Integrity",
    "axis": "Impact",
    "input": "Anti-corruption.scale",
    "base": 3,
    "swing": -0.0014355649651518,
    "low": 0.0023882083867854,
    "high": 0.0009526434216335,
    "abs_swing": 0.0014355649651518
  },
  {
    "topic": "T3 Green Finance & Integrity",
    "axis": "Impact",
    "input": "Anti-corruption.prob",
    "base": 3,
    "swing": 0.0009906617118775,
    "low": 0.0033867492941959,
    "high": 0.0043774110060734,
    "abs_swing": 0.0009906617118775
  },
  {
    "topic": "T3 Green Finance & Integrity",
    "axis": "Impact",
    "input": "Green-fin-access.scale",
    "base": 3,
    "swing": 0.1471135950712563,
    "low": -0.0704534576307911,
    "high": 0.0766601374404651,
    "abs_swing": 0.1471135950712563
  },
  {
    "topic": "T3 Green Finance & Integrity",
    "axis": "Impact",
    "input": "Green-fin-access.prob",
    "base": 4,
    "swing": 0.2936956034992222,
    "low": -0.1519989471399809,
    "high": 0.1416966563592412,
    "abs_swing": 0.2936956034992222
  },
  {
    "topic": "T3 Green Finance & Integrity",
    "axis": "Impact",
    "input": "SC-human-rights.scale",
    "base": 3,
    "swing": 0.0064865012106087,
    "low": 0.0016233271963237,
    "high": 0.0081098284069325,
    "abs_swing": 0.0064865012106087
  },
  {
    "topic": "T3 Green Finance & Integrity",
    "axis": "Impact",
    "input": "SC-human-rights.prob",
    "base": 3,
    "swing": 0.0520685866640739,
    "low": 0.0031584383721958,
    "high": 0.0552270250362698,
    "abs_swing": 0.0520685866640739
  },
  {
    "topic": "T3 Green Finance & Integrity",
    "axis": "Financial",
    "input": "R-coc-spread.mag",
    "base": 3,
    "swing": 0.1445865429645345,
    "low": -0.0587657527838967,
    "high": 0.0858207901806378,
    "abs_swing": 0.1445865429645345
  },
  {
    "topic": "T3 Green Finance & Integrity",
    "axis": "Financial",
    "input": "R-csrd-compliance.mag",
    "base": 3,
    "swing": 0.1174238296314507,
    "low": -0.0411340656901311,
    "high": 0.0762897639413195,
    "abs_swing": 0.1174238296314507
  },
  {
    "topic": "T3 Green Finance & Integrity",
    "axis": "Financial",
    "input": "R-csddd-liab.mag",
    "base": 2,
    "swing": 0.0017429215618363,
    "low": -0.0006963996030453,
    "high": 0.0010465219587909,
    "abs_swing": 0.0017429215618363
  },
  {
    "topic": "T3 Green Finance & Integrity",
    "axis": "Financial",
    "input": "O-green-bond-prem.mag",
    "base": 3,
    "swing": 0.1489629146191182,
    "low": -0.0609081556614796,
    "high": 0.0880547589576385,
    "abs_swing": 0.1489629146191182
  },
  {
    "topic": "T3 Green Finance & Integrity",
    "axis": "Financial",
    "input": "O-coc-saving.mag",
    "base": 3,
    "swing": 0.1453270516978997,
    "low": -0.0627537097069956,
    "high": 0.082573341990904,
    "abs_swing": 0.1453270516978997
  },
  {
    "topic": "T3 Green Finance & Integrity",
    "axis": "Financial",
    "input": "O-tender-esg.mag",
    "base": 2,
    "swing": 0.1080164544787325,
    "low": -0.0208639202095328,
    "high": 0.0871525342691996,
    "abs_swing": 0.1080164544787325
  }
],
  robustness: [
  {
    "scheme": "Equal",
    "topic": "T1 Water Resilience & Equitable Access",
    "impact_mean": 3.98,
    "financial_mean": 3.07,
    "in_target_zone": true
  },
  {
    "scheme": "Equal",
    "topic": "T2 Digital & Cyber Infrastructure",
    "impact_mean": 3.08,
    "financial_mean": 2.74,
    "in_target_zone": true
  },
  {
    "scheme": "Equal",
    "topic": "T3 Green Finance & Integrity",
    "impact_mean": 3.24,
    "financial_mean": 2.42,
    "in_target_zone": false
  },
  {
    "scheme": "Regulator-heavy",
    "topic": "T1 Water Resilience & Equitable Access",
    "impact_mean": 3.98,
    "financial_mean": 3.07,
    "in_target_zone": true
  },
  {
    "scheme": "Regulator-heavy",
    "topic": "T2 Digital & Cyber Infrastructure",
    "impact_mean": 3.08,
    "financial_mean": 2.75,
    "in_target_zone": true
  },
  {
    "scheme": "Regulator-heavy",
    "topic": "T3 Green Finance & Integrity",
    "impact_mean": 3.24,
    "financial_mean": 2.43,
    "in_target_zone": false
  },
  {
    "scheme": "Community-first",
    "topic": "T1 Water Resilience & Equitable Access",
    "impact_mean": 3.98,
    "financial_mean": 3.07,
    "in_target_zone": true
  },
  {
    "scheme": "Community-first",
    "topic": "T2 Digital & Cyber Infrastructure",
    "impact_mean": 3.08,
    "financial_mean": 2.75,
    "in_target_zone": true
  },
  {
    "scheme": "Community-first",
    "topic": "T3 Green Finance & Integrity",
    "impact_mean": 3.24,
    "financial_mean": 2.42,
    "in_target_zone": false
  },
  {
    "scheme": "Investor-first",
    "topic": "T1 Water Resilience & Equitable Access",
    "impact_mean": 3.98,
    "financial_mean": 3.07,
    "in_target_zone": true
  },
  {
    "scheme": "Investor-first",
    "topic": "T2 Digital & Cyber Infrastructure",
    "impact_mean": 3.08,
    "financial_mean": 2.75,
    "in_target_zone": true
  },
  {
    "scheme": "Investor-first",
    "topic": "T3 Green Finance & Integrity",
    "impact_mean": 3.24,
    "financial_mean": 2.42,
    "in_target_zone": false
  }
],
};
